using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Mikejzx.ChatServer
{
    public class ChatRoom
    {
        // Owner of the room.  Null if the server owns it.
        public ChatServerClient? owner;

        // Name of the room
        public string name;

        // Room topic.
        public string topic;

        // Users in the room.
        public List<ChatServerClient> clients = new List<ChatServerClient>();

        // Whether the room is encrypted.
        //
        // Note that the server never actually sees the private key; the key
        // is generated by the clients through a password that they should each
        // know.  This is a form of end-to-end encryption.
        public bool isEncrypted;

        // True if the room is a 'global room' managed by the server.
        private bool m_IsGlobal;
        public bool IsGlobal { get => m_IsGlobal; }

        public ChatRoom(ChatServerClient? owner, string name, string topic, bool isEncrypted=false, bool isGlobal=false)
        {
            this.owner = owner;
            this.name = name;
            this.topic = topic;
            this.isEncrypted = isEncrypted;
            this.m_IsGlobal = isGlobal;

            clients.Clear();

            // Add the owner to the clients list.
            if (owner is not null)
                clients.Add(owner);
        }
    }
}
